import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-red-500 px-6">
          <h6>Logo</h6>
          <ul>
          <li>About</li>
          <li>Service</li>
          <li>Contact</li>
          </ul>
        </nav>
       <div className="h-screen">
       {children}
       </div>
        <footer>
          This my footer
        </footer>
        </body>
    </html>
  );
}
